"""add tree and components

Revision ID: a664ed9969df
Revises: 9e3cfc0159f5
Create Date: 2026-01-26 13:42:37.104743

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a664ed9969df"
down_revision: str | None = "9e3cfc0159f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trees",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trees_id"), "trees", ["id"], unique=False)
    op.create_table(
        "individuals",
        sa.Column("tree_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("patronymic", sa.String(length=100), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="gender_types"),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_date_precision", sa.String(length=10), nullable=True),
        sa.Column("death_date", sa.Date(), nullable=True),
        sa.Column("death_date_precision", sa.String(length=10), nullable=True),
        sa.Column("birth_place", sa.Text(), nullable=True),
        sa.Column("death_place", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tree_id"], ["trees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_individuals_id"), "individuals", ["id"], unique=False)
    op.create_index(
        "ix_individuals_tree_name",
        "individuals",
        [
            "tree_id",
            sa.literal_column("lower(first_name)"),
            sa.literal_column("lower(last_name)"),
        ],
        unique=False,
    )
    op.create_table(
        "tree_access",
        sa.Column("tree_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("nothing", "viewer", "editor", "owner", name="tree_access_levels"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tree_id"], ["trees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tree_id", "user_id"),
    )
    op.create_table(
        "blood_relations",
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("parent_id != child_id", name="no_self_parent"),
        sa.ForeignKeyConstraint(["child_id"], ["individuals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["individuals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_id", "child_id", name="pk_blood_relation"),
        sa.UniqueConstraint("parent_id", "child_id", name="unique_parent_child"),
    )
    op.create_table(
        "marriages",
        sa.Column("father_id", sa.UUID(), nullable=False),
        sa.Column("mother_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("marriage_place", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["father_id"], ["individuals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mother_id"], ["individuals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("father_id", "mother_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("marriages")
    op.drop_table("blood_relations")
    op.drop_table("tree_access")
    op.drop_index("ix_individuals_tree_name", table_name="individuals")
    op.drop_index(op.f("ix_individuals_id"), table_name="individuals")
    op.drop_table("individuals")
    op.drop_index(op.f("ix_trees_id"), table_name="trees")
    op.drop_table("trees")
    # ### end Alembic commands ###

    conn = op.get_bind()
    _ = conn.execute(sa.text("DROP TYPE IF EXISTS gender_types"))
    _ = conn.execute(sa.text("DROP TYPE IF EXISTS tree_access_levels"))
